# Site settings
title: "Actrice - Mannequin commercial - Diane Martin"
header: Diane Martin
email: "dianemartin.contact@gmail.com"
og_description: "Actrice, mannequin commercial - Paris, France - Tournage, cinéma, audiovisuel, théâtre, audiovisuel, shooting, publicité"
description: "Actrice, mannequin commercial - Paris, France - Tournage, cinéma, audiovisuel, théâtre, shooting, publicité"
subheader: Actress & Model
url: ""
baseurl: ""
facebook_username: "dianemartin.contact"
instagram_username: "diane_martin_"

# Owner/author information
owner:
  name: Diane Martin
  favicon: favicon.png
  info: Site Diane Martin

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

exclude: ["less","node_modules","README.md"]